import type { Metadata } from "next";
import { Inter } from "next/font/google";
import local from 'next/font/local';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const chaney = local({
  src: [
    {
      path: '../public/font/chaney-ultraextended-webfont.woff',
      weight: '800',
    },
  ],
  variable: '--font-chaney',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chaney.variable} ${chaney.className}`}>
        {children}
      </body>
    </html>
  );
}
